config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    resources :books, only: [:create, :destroy, :edit]
 end

  resources :books, only: [:index, :show] do
    resources :pages
  end

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :pages
  # scope :ordered, :order => "name DESC"
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :book

  mount_uploader :image, ComicUploader
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books, dependent: :destroy
  validates :name, presence: true,
                   length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.includes(:user).order("users.name ASC")
  end

  def show
    @book = Book.find(params[:id])
    @pages = @book.pages
  end

  def create
    @user = User.find(params[:user_id])
    @book = @user.books.create(book_params)
    redirect_to user_path @user
  end

  def destroy
    @user = User.find(params[:user_id])
    @book = @user.books.find(params[:id])
    @book.destroy
    redirect_to user_path(@user)
  end

  private
  def book_params
    params.require(:book).permit(:title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def new
    @page = Page.new
    @book = Book.find(params[:book_id])
  end

  def create
    @book = Book.find(params[:book_id])
    @page = @book.pages.create(page_params)
    redirect_to book_page_path(@book, @page)
  end

  def show
    @page = Page.find(params[:id])
  end

  private

  def page_params
    params.require(:page).permit(:title,:caption,:image)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # inherit from Devise, so we can benefit from any updates in the far-future

  before_action :configure_permitted_parameters

  def new
    super
  end

  def create
    super
    # add custom create logic here
    # @user = User.new(devise_params)
    #
    # if @user.save
    #   redirect_to @user
    # else
    #   render 'new'
    # end
  end

  def update
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name,:description,
       :email, :password, "password_confirmation") }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user
      else
        render 'edit'
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

    private
      def user_params
        params.require(:user).permit(:name,:description)
      end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_book.html.erb
<!-- <div> -->
<tr>
  <td>
    <%= link_to book.user.name, user_path(book.user) %>
  </td>
  <td>
    <%= link_to book.title, book %>
  </td>
</tr>
<!-- <span><small><%= link_to 'Destroy Book', [book.user, book], method: :delete, data: { confirm: 'Are you sure?' } %></small></span> -->
<!-- </div> -->

app/views/books/_form.html.erb
<%= form_for([@user, @user.books.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/index.html.erb
<h1>List of Comic Books</h1>
<table>
    <%= render @books %>
</table>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<% @pages.each do |page| %>
  <div class="">
    <%= link_to "#{page.title}", book_page_path(@book,page) %>
  </div>
<% end %>
<div class="">
  <%= link_to 'Add a page', new_book_page_path(@book) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en>
  <head>
    <title>Komikb00k</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="row" data-equalizer>
      <div id="topLeft" class="medium-4 columns box" data-equalizer-watch>
        <%= link_to(image_tag("logos/logo.png", width: '110'), root_path) %>
        <li><%= link_to "Home",       root_path %></li>
        <li>
          <a href="#" data-dropdown="hover1" data-options="is_hover:true; hover_timeout:5000">Account &raquo;</a>
          <ul id="hover1" class="f-dropdown" data-dropdown-content>
            <% if user_signed_in? %>
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
          <% if !user_signed_in? %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        <li><%= link_to 'Other Komikb00ks', root_path %></li>
        <li><%= link_to 'Other Authors', users_path %></li>

      </div>
      <div id="topRight" class="medium-7 columns box" data-equalizer-watch>
        <div id="masthead">
          <%= link_to(image_tag("logos/logo.png", width: '110'), root_path) %>
          <span><%= current_user.name if current_user %></span>
        <ul class="inline-list">
          <li><%= link_to 'More comics', root_path %></li>
        </ul>
        </div>
      </div>
    </div>

    <div id="content" class="row">
      <div class="medium-12 columns box">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>

    <div class="row">
      <footer class="footer">
        <div class="medium-12 columns">
          Footer
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for ([@book, @book.pages.build]) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@page.errors.count, "error") %> prohibited
        this page from being saved:
      </h2>
      <ul>
        <% @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </p>

  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pages/_navigation.html.erb
<ul class="nav button-group round">
  <li><%= link_to '|<', root_path, class: "button tiny" %></li>
  <li><%= link_to '<', root_path, class: "button tiny" %></li>
  <li><%= link_to '?', root_path, class: "button tiny" %></li>
  <li><%= link_to '>', root_path, class: "button tiny" %></li>
  <li><%= link_to '>|', root_path, class: "button tiny" %></li>
</ul>

app/views/pages/new.html.erb
<h1>Add a new Page</h1>
<%= render 'form' %>
<%= link_to 'Back to Book', book_path(@book) %>

app/views/pages/show.html.erb
<div class="row">
  <div class="medium-12 columns">
    <ul class="small-block-grid-1">
      <h1><%= @page.title %></h1>
      <li><%= image_tag(@page.image, id: "comic-panel") %></li>
      <small><%= @page.caption %></small>
    </ul>
    <div class="small-block-grid-1">
      <%= render 'navigation' %>
    </div>
  </div>
</div>
<div>Back to <%= link_to("#{@page.book.title}",@page.book) %></div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit a new User</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>List of Authors</h1>
<%= link_to 'New Author', new_user_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><strong><%= user.name %></strong></td>
      <td><%= user.description %></td>
      <td><small><%= link_to 'Show', user_path(user) %></small></td>
      <td><small><%= link_to 'Edit', edit_user_path(user) %></small></td>
      <td><small><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?'} %></small></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Add a new User</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>User Name: <%= @user.name %></h1>
<h4>Description: <%= @user.description %></h4>

<h3>Comic Books</h3>
<table>
  <%= render @user.books %>
</table>

<h2>Add a book:</h2>
      <%= render 'books/form' %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>komikb00k</h1>
<p>A list of all the comics to view.</p>